apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-bot
  template:
    metadata:
      labels:
        app: basic-bot
    spec:
      containers:
        - name: basic-bot
          image: basicbotacr.azurecr.io/basic-bot:ingress-v2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basic-bot
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: basic-bot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-bot-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - zhijiebasicbot.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: zhijiebasicbot.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basic-bot
            port:
              number: 80
      - path: /api/messages
        pathType: Prefix
        backend:
          service:
            name: basic-bot
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <Your-Email>
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux